. "$PSScriptroot\rg_hub.ps1"
. "$PSScriptroot\vnet_hub.ps1"
. "$PSScriptroot\private_dns_zones.ps1"
. "$PSScriptroot\dns_private_resolver.ps1"
. "$PSScriptroot\fw_policies.ps1"
. "$PSScriptroot\firewall.ps1"